### ISSUE TITLE
支持双目吗？

### ISSUE THREAD

**Issue by why-freedom** [HeYijia/PL-VIO#1]
贺博，您好，这个版本支持双目吗？

**Comment by HeYijia** [comment]
这版本不支持，双目 line 的代码被我删掉了。我没有充分测试过，你可以很容易的加上去。

**Comment by why-freedom** [comment]
我加了双目之后发现报这个问题：好像是求解雅克比的问题，我后端是按找你的代码，没动。不知道这个是什么原因？烦劳贺博指点一下。

Error in evaluating the ResidualBlock.

There are two possible reasons. Either the CostFunction did not evaluate and fill all    
residual and jacobians that were requested or there was a non-finite value (nan/infinite)
generated during the or jacobian computation. 

Residual Block size: 3 parameter blocks x 2 residuals

For each parameter block, the value of the parameters are printed in the first column   
and the value of the jacobian under the corresponding residual. If a ParameterBlock was 
held constant then the corresponding jacobian is printed as 'Not Computed'. If an entry 
of the Jacobian/residual array was requested but was not written to by user code, it is 
indicated by 'Uninitialized'. This is an error. Residuals or Jacobian values evaluating 
to Inf or NaN is also an error.  

Residuals:               -0           -0 

Parameter Block 0, size: 7

    -1.70509 |            0            0 
     6.96999 |            0            0 
    -4.45992 |            0            0 
    -0.24007 |            0            0 
   -0.771844 |            0            0 
   -0.273616 |            0            0 
    0.521304 |            0            0 

Parameter Block 1, size: 7

  -0.0216401 | Not Computed  Not Computed  
   -0.064677 | Not Computed  Not Computed  
  0.00981073 | Not Computed  Not Computed  
 -0.00770718 | Not Computed  Not Computed  
   0.0104993 | Not Computed  Not Computed  
    0.701753 | Not Computed  Not Computed  
    0.712301 | Not Computed  Not Computed  

Parameter Block 2, size: 4

           0 |         -nan         -nan 
           0 |         -nan         -nan 
           0 |         -nan         -nan 
           0 |         -nan         -nan
