### ISSUE TITLE
为什么我的rviz没有一点图像

### ISSUE THREAD

**Issue by JuexiaOfficial** [HeYijia/PL-VIO#17]
![image](https://github.com/HeYijia/PL-VIO/assets/116532995/7659b943-4bf8-424e-aa9a-0abc24f59b9a)

**Comment by JuexiaOfficial** [comment]
![image](https://github.com/HeYijia/PL-VIO/assets/116532995/3666a9a9-bd68-47cd-9042-1d193b14e3ae)

**Comment by shuiyigong** [comment]
请问你是怎么解决的？

**Comment by JuexiaOfficial** [comment]
> 请问你是怎么解决的？
好像是话题的原因吧？看看有没有订阅对。时间太远了，我也记不太清了

**Comment by JuexiaOfficial** [comment]
@shuiyigong 好像是话题没有订阅对？时间太长了，记不太清了
